# Butterfly 主题配置

# 导航菜单
menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  游戏: /game/ || fas fa-gamepad
  关于: /about/ || fas fa-user

# 搜索
search:
  enable: false

# 代码高亮
highlight_theme: default
highlight_copy: true
highlight_lang: true
highlight_shrink: true

# 社交链接
social:
  fab fa-github: https://github.com/LanMercer || Github

# 页脚
footer:
  owner:
    enable: true
    since: 2024
  custom_text: 用 ❤️ 记录每一次冒险

# 文章元信息
post_meta:
  page:
    date_type: both
    date_format: relative
    categories: true
    tags: true
    wordcount: false

# TOC
toc:
  post: true
  page: false
  number: true
  expand: true

# 侧边栏
aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  card_author: true
  card_announcement: true
  card_recent_post: true
  card_categories: true
  card_tags: true
  card_archives: true
  card_webinfo: true
